# Generated by Django 4.1.2 on 2022-11-27 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_created_at_player_description_player_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='owner',
        ),
    ]
