# Generated by Django 4.1.2 on 2022-11-27 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_remove_player_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='player',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='player',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
